export const stockList = [
  { value: "india-vix-chart", label: "India VIX", indices: true },
  { value: "us-30-chart", label: "Dow Jones Industrial Average (DJI)", indices: true },
  { value: "bank-nifty-chart", label: "BANKNIFTY", indices: true },
  { value: "s-p-cnx-nifty-chart", label: "NIFTY", indices: true },
  { value: "dr-reddys-laboratories-chart", label: "DRREDDY" },
  { value: "cipla-chart", label: "CIPLA" },
  { value: "mundra-port-special-eco.-zone-chart", label: "ADANIPORTS" },
  { value: "bharti-airtel-chart", label: "BHARTIARTL" },
  { value: "mahindra---mahindra-chart", label: "M&M" },
  { value: "grasim-industries-chart", label: "GRASIM" },
  { value: "tech-mahindra-chart", label: "TECHM" },
  { value: "ntpc-chart", label: "NTPC" },
  { value: "sun-pharma-advanced-research-chart", label: "SUNPHARMA" },
  { value: "hindalco-industries-chart", label: "HINDALCO" },
  { value: "wipro-ltd-chart", label: "WIPRO" },
  { value: "power-grid-corp.-of-india-chart", label: "POWERGRID" },
  { value: "hero-motocorp-chart", label: "HEROMOTOCO" },
  { value: "oil---natural-gas-corporation-chart", label: "ONGC" },
  { value: "asian-paints-chart", label: "ASIANPAINT" },
  { value: "united-phosphorus-chart", label: "UPL" },
  { value: "gail-(india)-chart", label: "GAIL" },
  { value: "bharti-infratel-ltd-chart", label: "INFRATEL" },
  { value: "ultratech-cement-chart", label: "ULTRACEMCO" },
  { value: "bajaj-auto-chart", label: "BAJAJ-AUTO" },
  { value: "axis-bank-chart", label: "AXISBANK" },
  { value: "itc-chart", label: "ITC" },
  { value: "jsw-steel-chart", label: "JSWSTEEL" },
  { value: "eicher-motors-chart", label: "EICHERMOT" },
  { value: "nestle-chart", label: "Nestle India Ltd" },
  { value: "hcl-technologies-chart", label: "HCLTECH" },
  { value: "reliance-industries-chart", label: "RELIANCE" },
  { value: "tata-motors-ltd-chart", label: "TATAMOTORS" },
  { value: "bajaj-finance-chart", label: "BAJFINANCE" },
  { value: "icici-bank-ltd-chart", label: "ICICIBANK" },
  { value: "tata-consultancy-services-chart", label: "TCS" },
  { value: "indusind-bank-chart", label: "INDUSINDBK" },
  { value: "britannia-industries-chart", label: "BRITANNIA" },
  { value: "tata-steel-chart", label: "TATASTEEL" },
  { value: "zee-entertainment-enterprises-chart", label: "ZEEL" },
  { value: "bharat-petroleum-chart", label: "BPCL" },
  { value: "housing-development-finance-chart", label: "HDFC" },
  { value: "hdfc-standard-life-chart", label: "HDFCLIFE" },
  { value: "larsen---toubro-chart", label: "LT" },
  { value: "infosys-chart", label: "INFY" },
  { value: "coal-india-chart", label: "COALINDIA" },
  { value: "indian-oil-corporation-chart", label: "IOC" },
  { value: "state-bank-of-india-chart", label: "SBIN" },
  { value: "hindustan-unilever-chart", label: "HINDUNILVR" },
  { value: "titan-industries-chart", label: "TITAN" },
  { value: "maruti-suzuki-india-chart", label: "MARUTI" },
  { value: "kotak-mahindra-bank-chart", label: "KOTAKBANK" },
  { value: "bajaj-finserv-limited-chart", label: "BAJAJFINSV" },
  { value: "shree-cements-chart", label: "SHREECEM" },
  { value: "hdfc-bank-ltd-chart", label: "HDFCBANK" },
];
